
# See: https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
# For 1D observation space, a 2 layers fully connected net is used with:
# 64 units (per layer) for PPO/A2C/DQN
# 256 units for SAC
# [400, 300] units for TD3/DDPG (values are taken from the original TD3 paper)

policy_kwargs:
  net_arch:
    pi: [16, 8]
    qvf: [16, 8]   # Assigned to "qf" or "vf" depending on algo type
  activation_fn: 
    _target_: torch.nn.ReLU
