defaults:
  - env: discrete_actions
  - base_nn
  - _self_

agent:
  policy:
    _target_: bandits.policy_sb3.SB3PolicyDQN
    policy: "MlpPolicy"
    learning_rate: 0.0001
    buffer_size: 1000000
    learning_starts: 100
    batch_size: 32
    tau: 1.0
    gamma: 0.99
    train_freq: 4
    gradient_steps: 1
    seed: ${RND_SEED}
    verbose: ${verbosity}

# TERMINATION Specific for DQN
env:
  wrapper:
    env:
      on_terminate: -1 # A value policy, do not learn a strategy (like PPO and others)
