defaults:
  - env: discrete_actions
  - base_linear
  - override env/state_selector@env.state_selector_train: df_fullsequential #df_randombuffer
  - _self_

agent:
  policy:
    _target_: bandits.policy_linucb_kfoofw.LinUCBPolicy_kfoofw
    learning_rate: 0.9

