
_partial_: true
_target_: bandits.datasource.adbms_dataframe.ADBMSBufferCacheStatesSequentialSelector
qpslat_w: "01"
topdown: True
context_elems: ${..observations.elems} #tuner.env
normalize: ${...NORMALIZE_OBS} # tuner.

