
server_name: mariadb
# History:
# 10.11.6 does not update innodb_buffer_pool_read_requests, see https://jira.mariadb.org/browse/MDEV-31309
# 2024, August, the Long Term support release is 11.4.3
server_version: 11.1.3 

other_knobs:
  - tmp_table_size # involved with max_heap_table_size in temporary table creation in MySQL (user created and those created automatically during evaluation of certain statements).
  - max_heap_table_size #  sets the maximum size of an user-created table that can be created in memory
  - innodb_log_buffer_size # Not Dynamic! used to control the size of the buffer that stores transaction log information in the InnoDB storage engine. Default is 8MB
# - innodb_change_buffering # Removed in 10.11+ Control/determines which form of change buffering, if any, to use: insert, deltes, changes, purges, all, none

# See https://mariadb.com/kb/en/server-status-variables
global_status:
  - Bytes_received
  - Connections
  - threads_created
  - threads_running
  - threads_connected
  - max_used_connections # 
  - aborted_clients #
  - aborted_connects #
  - created_tmp_files # How many temporary files mysqld has created
  - created_tmp_tables # The number of internal temporary tables created by the server while executing statements
  - created_tmp_disk_tables # The number of internal on-disk temporary tables created by the server while executing statements
  - binlog_cache_disk_use # The number of transactions that used the temporary binary log cache but that exceeded the value of binlog_cache_size and used a temporary file to store statements from the transaction.
  - binlog_stmt_cache_disk_use
  - handler_delete # The number of times that rows have been deleted from tables
  - handler_update # The number of requests to update a row in a table
  - handler_write # The number of requests to insert a row in a table
  - innodb_pages_created # The number of pages created by operations on InnoDB tables
  - innodb_pages_read # The number of pages read from the InnoDB buffer pool by operations on InnoDB tables
  - innodb_pages_written # The number of pages written by operations on InnoDB tables
  - innodb_rows_deleted 
  - innodb_rows_inserted
  - innodb_rows_read
  - innodb_rows_updated
  - innodb_row_lock_current_waits
  - innodb_row_lock_time
  - innodb_row_lock_time_avg
  - innodb_row_lock_time_max
  - innodb_row_lock_waits
#  - innodb_buffer_pool_pages_latched # EXPENSIVE BUT...? The number of latched pages in the InnoDB buffer pool. These are pages currently being read or written, or that cannot be flushed or removed for some other reason. Calculation of this variable is expensive, so it is available only when the UNIV_DEBUG system is defined at server build time
  - innodb_buffer_pool_bytes_data # The total number of bytes in the InnoDB buffer pool containing data. The number includes both dirty and clean pages
  - innodb_buffer_pool_bytes_dirty # The total current number of bytes held in dirty pages in the InnoDB buffer pool
  - innodb_buffer_pool_pages_data # The total number of pages in the InnoDB buffer pool containing data. The number includes both dirty and clean pages
  - innodb_buffer_pool_pages_total # Total count of pages in the memory buffer
  - innodb_buffer_pool_pages_free  # Free pages count in the memory buffer 
  - innodb_buffer_pool_pages_misc # Is = innodb_buffer_pool_pages_total-innodb_buffer_pool_pages_free.The number of pages that are busy because they have been allocated for administrative overhead such as row locks or the adaptive hash index
  - innodb_buffer_pool_reads         # The number of physical reads of a page from disk, ie, cache misses because not satisfied from the buffer pool
  - innodb_buffer_pool_read_requests # NA in MariaDB. The number of read requests of a page from the Cache that came either from disk or from the buffer pool
  - innodb_buffer_pool_wait_free # Total number of waits for pages to be flushed first from the InnoDB buffer pool
  - innodb_buffer_pool_write_requests # The number of writes done to the InnoDB buffer pool
  - innodb_data_read # Number of InnoDB bytes read since server startup (not to be confused with Innodb_data_reads).
  - innodb_data_reads # Number of InnoDB read operations (not to be confused with Innodb_data_read).
  - innodb_data_writes # Number of InnoDB write operations.
  - innodb_data_written # Number of InnoDB bytes written since server startup. Approximation, see Doc: https://mariadb.com/kb/en/innodb-status-variables/#innodb_data_read

# Other collected information data to collect or not (comment the line)
# innodb_metrics with a "Select name, count from information_schema.<elem> where enabled=1"
# innodb_buffer_pool_stats " with "SELECT * from information_schema.innodb_buffer_pool_stats", => only 1 row of results with  POOL_ID | POOL_SIZE | FREE_BUFFERS | DATABASE_PAGES | OLD_DATABASE_PAGES | MODIFIED_DATABASE_PAGES | PENDING_DECOMPRESS | PENDING_READS | PENDING_FLUSH_LRU | PENDING_FLUSH_LIST | PAGES_MADE_YOUNG | PAGES_NOT_MADE_YOUNG | PAGES_MADE_YOUNG_RATE | PAGES_MADE_NOT_YOUNG_RATE | NUMBER_PAGES_READ | NUMBER_PAGES_CREATED | NUMBER_PAGES_WRITTEN | PAGES_READ_RATE | PAGES_CREATE_RATE | PAGES_WRITTEN_RATE | NUMBER_PAGES_GET | HIT_RATE | YOUNG_MAKE_PER_THOUSAND_GETS | NOT_YOUNG_MAKE_PER_THOUSAND_GETS | NUMBER_PAGES_READ_AHEAD | NUMBER_READ_AHEAD_EVICTED | READ_AHEAD_RATE | READ_AHEAD_EVICTED_RATE | LRU_IO_TOTAL | LRU_IO_CURRENT | UNCOMPRESS_TOTAL | UNCOMPRESS_CURRENT
# LATER:
# SELECT * FROM INFORMATION_SCHEMA.CLIENT_STATISTICS (https://mariadb.com/kb/en/information-schema-client_statistics-table/)
# SET GLOBAL userstat=1; (Enable user stats module, https://mariadb.com/kb/en/user-statistics/)
# or SHOW CLIENT_STATISTICS
# FLUSH CLIENT_STATISTICS
information_schemas:
  - innodb_metrics
  - innodb_buffer_pool_stats
  - innodb_buffer_page
  - innodb_lock_waits
  - innodb_locks

# Mapping of names to do with innodb_metrics schema
information_schemas_mapping:
  # innodb_buffer_pool_read_requests is not well updated in MariaDB (bug resolved with the conclusion that the Glob Status Var can NOT be updated as expected!!).https://jira.mariadb.org/browse/MDEV-31309
  innodb_buffer_pool_read_requests:
    schema: innodb_metrics
    name: buffer_pool_read_requests
  innodb_buffer_pool_reads:
    schema: innodb_metrics
    name: buffer_pool_reads
  innodb_buffer_pool_write_requests:
    schema: innodb_metrics
    name: buffer_pool_write_requests
  innodb_buffer_pool_wait_free:
    schema: innodb_metrics
    name: buffer_pool_wait_free
    