learn:
  _target_: bandits.reward.ADBMSBufferCacheRewardNormal3
  action_minmax: ${...actions.minmax}




test:
  _target_: bandits.reward.ADBMSBufferCacheRewardNormal3
  action_minmax: ${...actions.minmax}


