learn:
  _target_: bandits.reward.ADBMSBufferCacheRewardNormal
  action_minmax: ${...actions.minmax}




test:
  _target_: bandits.reward.ADBMSBufferCacheRewardNormal
  action_minmax: ${...actions.minmax}


