elems:
  - db_size_mb
  - sysbench_filtered.latency_mean
  - observation.normalized_buf_size
  - observation.cache_used_pages_ratio
  - observation.cache_hit_ratio
  - extra_info.usage.qps
  - observation.write_wait_ratio
  - extra_info.global_status.innodb_buffer_pool_wait_free_diff
  - extra_info.global_status.innodb_data_reads_diff
  - extra_info.global_status.innodb_data_written_diff
  - extra_info.global_status.max_used_connections_end
  - extra_info.global_status.threads_running_end
#  - extra_info.global_status.innodb_buffer_pool_bytes_dirty_end
#  - extra_info.global_status.innodb_buffer_pool_pages_free_end
  - extra_info.global_status.innodb_buffer_pool_bytes_dirty_diff
  - extra_info.global_status.innodb_buffer_pool_pages_free_diff
  - extra_info.global_status.information_schema.innodb_metrics.lock_row_lock_time_max
  - extra_info.global_status.information_schema.innodb_metrics.lock_row_lock_waits
  - extra_info.global_status.information_schema.innodb_metrics.os_pending_reads
  - extra_info.global_status.information_schema.innodb_metrics.os_pending_writes
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PAGES_READ_RATE
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PAGES_CREATE_RATE
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.READ_AHEAD_RATE
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.READ_AHEAD_EVICTED_RATE
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PAGES_MADE_YOUNG_RATE
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.DATABASE_PAGES
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PENDING_DECOMPRESS
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PENDING_READS
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PENDING_FLUSH_LRU
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.PENDING_FLUSH_LIST
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.YOUNG_MAKE_PER_THOUSAND_GETS
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.LRU_IO_TOTAL
  - extra_info.global_status.information_schema.innodb_buffer_pool_stats.LRU_IO_CURRENT